### ISSUE TITLE
Home page public view testing 1

### ISSUE THREAD

**Issue by 9atrotte** [9atrotte/13IA#12]
please get a public view and opinion on the home page and a stakeholder opinion

- [x] - public
- [ ] - stakeholder

**Comment by 9atrotte** [comment]
Public
Jamie:
style tables, needs titles, likes background, remove background of the slide show, order by position on left table.

@YelloElefant

**Comment by 9atrotte** [comment]
Public
Damion:
style the tables, add a better background, style the slideshow, remove the arrow if no drop down

@YelloElefant

**Comment by YelloElefant** [comment]
Stakeholer 
mr hay has said that the home page needs to be very simple with a blurb
also make the quickStandings table a history of winners table instead 
also a background image of the cup
