### ISSUE TITLE
PROGRESS REVIEW 1

### ISSUE THREAD

**Issue by YelloElefant** [9atrotte/13IA#49]

**Comment by YelloElefant** [comment]
things need to be planned in advance more as things are just getting done and not documented
so more issues need to be opened

**Comment by YelloElefant** [comment]
the website is starting to come together but the small things like links and consistency still needs to be worked on

**Comment by 9atrotte** [comment]
Jamie:
good initial development
promising signs of a visually impressive website
features employed already are good
project management is clear and concise

**Comment by YelloElefant** [comment]
IN CLOSING
project is going good so far but documentation is lacking
